[[constraint]]
  # Required: the root import path of the project being constrained.
  name = "github.com/tidepool-org/go-common"
  # Recommended: the version constraint to enforce for the project.
  # Note that only one of "branch", "version" or "revision" can be specified.
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
